### ISSUE TITLE
Readme inaccuracy

### ISSUE THREAD

**Issue by zabudskyi** [b1-systems/chef-handler-httpapi#1]
It seems it has to be 
`require "chef/handler/Httpapi"` in Usage section

**Comment by yeoldegrove** [comment]
@zabudskyi Just saw, that we use ``` require 'Httpapi.rb' ``` in our setup, which works out.
Are you fine with me updating it like this?

**Comment by zabudskyi** [comment]
@yeoldegrove Actually I used absolute path while testing. So your update is quite useful.
